import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import AuthProvider from "@/components/AuthProvider";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { Modal } from "@/components/Modal";
import "@/styles/_globals.scss";

const rubikFont = Rubik({
  variable: "--font-rubik",
  subsets: ["latin", "cyrillic"],
});

export const metadata: Metadata = {
  title: "Влада Спорт",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={rubikFont.variable} suppressHydrationWarning>
        <AuthProvider>
          <Header />
          <div className="page">{children}</div>
          <Footer />
          <Modal />
        </AuthProvider>
      </body>
    </html>
  );
}
